
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mentinkdata?useSSL=false&characterEncoding=UTF-8&serverTimezone=Asia/Seoul
    username: mentink
    password: "hackathon"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5InnoDBDialect

server:
  port: 8888